plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

version = libs.versions.trustkitVersionName.get()

android {
    namespace = 'com.datatheorem.android.trustkit'
    compileSdkVersion libs.versions.compileSdk.get().toInteger()

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        minSdkVersion libs.versions.minSdk.get().toInteger()
        versionCode libs.versions.trustkitVersionCode.get().toInteger()
        versionName project.version.toString()
        buildConfigField 'String', 'VERSION_NAME', "\"${project.version}\""
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
        targetCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
    }

    kotlinOptions {
        jvmTarget = libs.versions.jvmTarget.get()
    }
}

dependencies {
    implementation libs.androidx.annotation
    implementation libs.androidx.preference
    compileOnly libs.okhttp3
    compileOnly libs.okhttp2
    androidTestImplementation libs.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
    androidTestImplementation libs.mockito.core
    androidTestImplementation libs.awaitility
    androidTestImplementation libs.dexmaker.core
    androidTestImplementation libs.dexmaker.dx
    androidTestImplementation libs.dexmaker.mockito
    androidTestImplementation libs.okhttp3
    androidTestImplementation libs.google.play.services.base
}

// MavenCentral deployment gradle script
apply from: "${rootProject.projectDir}/deploymentScripts/publish-mavencentral.gradle"
